### ISSUE TITLE
scss syntax

### ISSUE THREAD

**Issue by nilshendriks** [sc8696/sublime-css-auto-comments#1]
For me it is not working with SCSS in ST 3 beta.

**Comment by sc8696** [comment]
What OS? It works fine for me in Windows and OSX on ST3 Beta in SCSS

Also be sure you have the latest version, it was updated to work in ST3 lately.

**Comment by nilshendriks** [comment]
Hi,

OS X 10.8.4

It has to do with the syntax set on the file. 
With syntax set to SCSS it doesn't work, with CSS it does.

Cheers,
Nils

**Comment by sc8696** [comment]
This could be due to no specific "scss" setting in the keymap, though it works with the "sass" setting for scss files for me on all platforms.

It may be fixed now but I have no idea as I can't seem to replicate your issue at all

**Comment by nilshendriks** [comment]
Oh, ok, I'll just use sass syntax highlighting instead of scss, no biggie :-)
